function PE_DSE = cleanDSE_PE(DedicatedPEDSE)
PE_DSE = table(DedicatedPEDSE.decomposer,...
    DedicatedPEDSE.delay_fifo_depth,...
    DedicatedPEDSE.num_input_ports,...
    DedicatedPEDSE.num_output_ports,...
    DedicatedPEDSE.isShared,...
    DedicatedPEDSE.output_select_mode,...
    DedicatedPEDSE.protocol,...
    DedicatedPEDSE.register_file_size,...
    DedicatedPEDSE.shared_slot_size,...
    DedicatedPEDSE.mappedareaTotalcellarea,...
    DedicatedPEDSE.mappedpowerTotal);
PE_DSE.Properties.VariableNames = ["decomposer",...
    "delay_fifo_depth",...
    "num_input_ports",...
    "num_output_ports",...
    "isShared",...
    "output_select_mode",...
    "protocol",...
    "register_file_size",...
    "shared_slot_size",...
    "mappedareaTotalcellarea",...
    "mappedpowerTotal"];

% encode categorical variable
PE_DSE.isShared = categorical(PE_DSE.isShared);
categories(PE_DSE.isShared)
isSharedCatergory = dummyvar(PE_DSE.isShared);
isSharedCatergory = array2table(isSharedCatergory);
isSharedCatergory.Properties
% encode categorical variable
PE_DSE.protocol = categorical(PE_DSE.protocol);
categories(PE_DSE.protocol)
protocolCatergory = dummyvar(PE_DSE.protocol);
protocolCatergory = array2table(protocolCatergory);
protocolCatergory.Properties
% encode categorical variable
PE_DSE.output_select_mode = categorical(PE_DSE.output_select_mode);
categories(PE_DSE.output_select_mode)
output_select_mode_catorgory = dummyvar(PE_DSE.output_select_mode);
output_select_mode_catorgory = array2table(output_select_mode_catorgory);
output_select_mode_catorgory.Properties
% Combined with Catergory Variable
PE_DSE = [isSharedCatergory, protocolCatergory,output_select_mode_catorgory,PE_DSE];
PE_DSE.isShared = [];
PE_DSE.protocol = [];
PE_DSE.output_select_mode = [];
end